version: '3'

services:
  go-webserver:
    image: rhysemmas/go-webserver:v2
    environment:
      - STATE=reset
    ports:
      - "8080:8080"
    depends_on:
      - envoy

  envoy:
    image: envoyproxy/envoy-alpine:v1.13.0
    command: --config-path /etc/envoy/envoy.yaml -l debug
    ports:
      - "10000:10000"
      - "9901:9901"
    volumes:
      - ./envoy/envoy.yaml:/etc/envoy/envoy.yaml:ro
